// ─── Contact Form — Admin Notification Email ──────────────────
export const contactAdminTemplate = ({
  name,
  email,
  phone,
  service,
  message,
}) => ({
  subject: `📩 New Contact Request from ${name}`,
  html: `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden;">
      <div style="background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%); padding: 32px; text-align: center;">
        <h1 style="color: #ffffff; margin: 0; font-size: 24px; letter-spacing: 2px;">INTALLIA</h1>
        <p style="color: #94a3b8; margin: 8px 0 0; font-size: 13px;">New Contact Form Submission</p>
      </div>
      <div style="padding: 32px; background: #ffffff;">
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-size: 13px; width: 35%;">👤 Full Name</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 600;">${name}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-size: 13px;">📧 Email</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 600;">${email}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-size: 13px;">📱 Phone</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 600;">${phone}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-size: 13px;">🛠️ Service</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 600;">${service || "Not specified"}</td>
          </tr>
        </table>
        <div style="margin-top: 24px;">
          <p style="color: #64748b; font-size: 13px; margin-bottom: 10px;">💬 Message</p>
          <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 16px; border-radius: 6px; color: #334155; line-height: 1.7;">
            ${message}
          </div>
        </div>
      </div>
      <div style="background: #f8fafc; padding: 16px 32px; text-align: center;">
        <p style="color: #94a3b8; font-size: 12px; margin: 0;">This email was auto-generated by Intallia Contact System</p>
      </div>
    </div>
  `,
});

// ─── Contact Form — User Confirmation Email ───────────────────
export const contactUserTemplate = ({ name }) => ({
  subject: `✅ We received your message — Intallia`,
  html: `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden;">
      <div style="background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%); padding: 32px; text-align: center;">
        <h1 style="color: #ffffff; margin: 0; font-size: 24px; letter-spacing: 2px;">INTALLIA</h1>
        <p style="color: #94a3b8; margin: 8px 0 0; font-size: 13px;">Building Tomorrow's Workforce</p>
      </div>
      <div style="padding: 40px 32px; background: #ffffff; text-align: center;">
        <div style="font-size: 48px; margin-bottom: 16px;">🎉</div>
        <h2 style="color: #0f172a; margin: 0 0 12px;">Thank you, ${name}!</h2>
        <p style="color: #64748b; line-height: 1.7; margin: 0 0 24px;">
          We've received your message and our team will get back to you within <strong>24 hours</strong>.
        </p>
        <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 16px; color: #1e40af; font-size: 14px;">
          In the meantime, feel free to explore our services or connect with us on social media.
        </div>
      </div>
      <div style="background: #f8fafc; padding: 16px 32px; text-align: center;">
        <p style="color: #94a3b8; font-size: 12px; margin: 0;">© ${new Date().getFullYear()} Intallia. All rights reserved.</p>
      </div>
    </div>
  `,
});

// ─── Newsletter — Welcome Email ───────────────────────────────
export const newsletterWelcomeTemplate = (email) => ({
  subject: `🎉 You're subscribed to Intallia Newsletter!`,
  html: `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden;">
      <div style="background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%); padding: 32px; text-align: center;">
        <h1 style="color: #ffffff; margin: 0; font-size: 24px; letter-spacing: 2px;">INTALLIA</h1>
        <p style="color: #94a3b8; margin: 8px 0 0; font-size: 13px;">Newsletter</p>
      </div>
      <div style="padding: 40px 32px; background: #ffffff; text-align: center;">
        <div style="font-size: 48px; margin-bottom: 16px;">📬</div>
        <h2 style="color: #0f172a; margin: 0 0 12px;">Welcome aboard!</h2>
        <p style="color: #64748b; line-height: 1.7; margin: 0 0 24px;">
          You've successfully subscribed to the Intallia newsletter with <strong>${email}</strong>.
          <br/>Expect insights on AI, Data Engineering, and Technology straight to your inbox.
        </p>
        <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 16px; color: #166534; font-size: 14px;">
          Stay tuned for upcoming updates, blogs, and exclusive offers!
        </div>
      </div>
      <div style="background: #f8fafc; padding: 16px 32px; text-align: center;">
        <p style="color: #94a3b8; font-size: 12px; margin: 0;">© ${new Date().getFullYear()} Intallia. All rights reserved.</p>
      </div>
    </div>
  `,
});
